ACCEPT_LICENSE="@FREE intel-ucode linux-fw-redistributable"

COMMON_FLAGS="-O2 -march=skylake -flto=thin -pipe"
HARDENING_FLAGS="-fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fstack-protector-strong -fstack-clash-protection -Wformat"

CFLAGS="${COMMON_FLAGS} ${HARDENING_FLAGS}"
CXXFLAGS="${COMMON_FLAGS} ${HARDENING_FLAGS} -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="-fuse-ld=lld -flto=thin -Wl,-O1 -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs"

CHOST="x86_64-pc-linux-gnu"

RUSTFLAGS="-C opt-level=3 -C linker-plugin-lto -C link-arg=-fuse-ld=lld -C link-arg=-Wl,-z,relro -C link-arg=-Wl,-z,now -C link-arg=-Wl,-z,pack-relative-relocs -C force-frame-pointers=yes"
CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS="${RUSTFLAGS} -C target-cpu=skylake"
CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER="clang"

VIDEO_CARDS="intel"
USE="dbus wayland vulkan -perl -X"

FEATURES="getbinpkg nodoc noinfo noman"

source make.local.conf
