CC="gcc"
CXX="g++"

GCC_COMMON="-O2 -march=skylake -pipe"
GCC_HARDENING="-fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fstack-protector-strong -fstack-clash-protection -Wformat -D_GLIBCXX_ASSERTIONS"

# CFLAGS="${GCC_COMMON} ${GCC_HARDENING}"
CFLAGS="-O2 -march=skylake -pipe -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fstack-protector-strong -fstack-clash-protection -Wformat -D_GLIBCXX_ASSERTIONS"
# CXXFLAGS="${GCC_COMMON} ${GCC_HARDENING}"
CXXFLAGS="-O2 -march=skylake -pipe -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fstack-protector-strong -fstack-clash-protection -Wformat -D_GLIBCXX_ASSERTIONS"
# FCFLAGS="${GCC_COMMON}"
FCFLAGS="-O2 -march=skylake -pipe"
# FFLAGS="${GCC_COMMON}"
FFLAGS="-O2 -march=skylake -pipe"

LDFLAGS="-fuse-ld=bfd -Wl,-O1 -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs"
RUSTFLAGS="-C opt-level=3 -C target-cpu=skylake -C linker=cc -C force-frame-pointers=yes"
